# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 07:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Immigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Palvelun nimi')),
                ('ingress', models.TextField(blank=True, null=True, verbose_name='Ingressi')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Kuvaus')),
                ('constraint', models.CharField(blank=True, default='', max_length=100, verbose_name='Palvelun rajaukset')),
                ('keywords', models.CharField(blank=True, default='', max_length=200, verbose_name='Avainsanat')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Voimassaolon alku')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Voimassaolon loppu')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Katuosoite')),
                ('address_extend', models.CharField(blank=True, default='', max_length=100, verbose_name='Osoitteen tarkennus')),
                ('organization', models.CharField(blank=True, default='', max_length=100, verbose_name='Järjestävä organisaatio')),
                ('contact_person', models.CharField(blank=True, default='', max_length=100, verbose_name='Yhteyshenkilö')),
                ('contact_person_phone', models.CharField(blank=True, default='', max_length=100, verbose_name='Yhteyshenkilön puhelin')),
                ('contact_email', models.CharField(blank=True, default='', max_length=100, verbose_name='Yhteyshenkilön sähköposti')),
                ('www', models.CharField(blank=True, default='', max_length=100, verbose_name='WWW-sivu')),
                ('facebook', models.CharField(blank=True, default='', max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, default='', max_length=100, verbose_name='Twitter')),
                ('age_group', models.ManyToManyField(blank=True, related_name='age_groups', to='services.Age', verbose_name='Ikäryhmä')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ServicePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='classification',
            field=models.ManyToManyField(blank=True, related_name='classifications', to='services.Study', verbose_name='Palvelun luokka'),
        ),
        migrations.AddField(
            model_name='service',
            name='finnish_skill',
            field=models.ManyToManyField(blank=True, related_name='finnish_skills', to='services.Study', verbose_name='Maahanmuuttotausta'),
        ),
        migrations.AddField(
            model_name='service',
            name='health',
            field=models.ManyToManyField(blank=True, related_name='healths', to='services.Health', verbose_name='Terveydentila / työkyky'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_path',
            field=models.ManyToManyField(blank=True, related_name='service_paths', to='services.ServicePath', verbose_name='Palvelupolku'),
        ),
        migrations.AddField(
            model_name='service',
            name='study',
            field=models.ManyToManyField(blank=True, related_name='studies', to='services.Study', verbose_name='Opiskelu'),
        ),
        migrations.AddField(
            model_name='service',
            name='target',
            field=models.ManyToManyField(blank=True, related_name='targets', to='services.Target', verbose_name='Tavoite'),
        ),
        migrations.AddField(
            model_name='service',
            name='unemployment_duration',
            field=models.ManyToManyField(blank=True, related_name='unemployment_durations', to='services.Duration', verbose_name='Työttömyyden kesto'),
        ),
    ]
