# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='keywords',
        ),
        migrations.AddField(
            model_name='service',
            name='post_address',
            field=models.TextField(blank=True, null=True, verbose_name='Postiosoite'),
        ),
    ]
