# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170614_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FinnishSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='classification',
            field=models.ManyToManyField(blank=True, related_name='classifications', to='services.Classification', verbose_name='Palvelun luokka'),
        ),
        migrations.AlterField(
            model_name='service',
            name='finnish_skill',
            field=models.ManyToManyField(blank=True, related_name='finnish_skills', to='services.FinnishSkill', verbose_name='Maahanmuuttotausta'),
        ),
    ]
