# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170616_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='finnish_skill',
        ),
        migrations.AddField(
            model_name='service',
            name='immigration',
            field=models.ManyToManyField(blank=True, related_name='immigration', to='services.Immigration', verbose_name='Maahanmuuttotausta'),
        ),
        migrations.DeleteModel(
            name='FinnishSkill',
        ),
    ]
