# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='integration',
            field=models.ManyToManyField(blank=True, related_name='integration', to='services.Health', verbose_name='Kotouttaminen'),
        ),
    ]
