# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20170620_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='open_ended',
            field=models.BooleanField(default=False, verbose_name='Voimassa toistaiseksi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='integration',
            field=models.ManyToManyField(blank=True, related_name='integration', to='services.Integration', verbose_name='Kotouttaminen'),
        ),
    ]
