# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20170620_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='constraint',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Palvelun rajaukset'),
        ),
    ]
