# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 09:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20170621_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='search_result_priority',
            field=models.PositiveIntegerField(blank=True, default=9, verbose_name='Hakutulosprioriteetti'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Kuvaus'),
        ),
    ]
