# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 12:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20170823_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description2',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Kuvaus 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='description3',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Kuvaus 3'),
        ),
        migrations.AddField(
            model_name='service',
            name='description4',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Kuvaus 4'),
        ),
    ]
