# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20170914_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='benefit_effect',
            field=models.TextField(blank=True, null=True, verbose_name='Vaikuttaako tukiin'),
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.TextField(blank=True, null=True, verbose_name='Toimija'),
        ),
    ]
