# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 08:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20171017_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Toimija'),
        ),
    ]
