# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20171017_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='service',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='service',
            name='www',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='WWW-sivu'),
        ),
    ]
