# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 08:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20171017_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Palevluntarjoajan viestilaatikko'),
        ),
    ]
