# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 13:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_service_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='labour_hire',
            field=models.BooleanField(default=False, verbose_name='Vuokratyö'),
        ),
        migrations.AlterField(
            model_name='service',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Palveluntarjoajan viestilaatikko'),
        ),
    ]
