# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20171107_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content_contact',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sisällön yhteyshenkilö'),
        ),
    ]
