# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_service_content_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ptv_service_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='PTV Palvelun id'),
        ),
    ]
