# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_service_ptv_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ptv_servicechannel_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='PTV Palvelukanavan id'),
        ),
    ]
