# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_service_ptv_servicechannel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='www',
            field=models.TextField(blank=True, null=True, verbose_name='Verkkosivu'),
        ),
    ]
