# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20180613_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='contact_email',
            field=models.TextField(blank=True, null=True, verbose_name='Sähköposti'),
        ),
        migrations.AlterField(
            model_name='service',
            name='contact_person_phone',
            field=models.TextField(blank=True, null=True, verbose_name='Puhelinnumero'),
        ),
    ]
