# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-03 17:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_auto_20180613_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='labour_hire',
        ),
        migrations.AlterField(
            model_name='service',
            name='organization',
            field=models.TextField(blank=True, default='', verbose_name='Järjestävä organisaatio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='www',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Verkkosivu'),
        ),
    ]
