# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-03 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_auto_20180903_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='constraint',
            field=models.TextField(blank=True, default='', verbose_name='Palvelun rajaukset'),
        ),
    ]
