# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-02 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20190402_1532'),
        ('services', '0024_service_labour_hire'),
    ]

    operations = [
    ]
